# Generated by Django 4.2.7 on 2023-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('w', models.FloatField()),
            ],
        ),
    ]
