# Generated by Django 4.2.7 on 2023-11-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer_main', '0002_tuple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Vector',
        ),
    ]
