# Generated by Django 4.2.7 on 2023-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer_main', '0005_alter_canvas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
