# Generated by Django 4.2.7 on 2023-11-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer_main', '0006_canvas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='image',
            field=models.ImageField(upload_to='canvas/'),
        ),
    ]
