# Generated by Django 4.2.7 on 2023-11-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer_main', '0007_alter_canvas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='image',
            field=models.BinaryField(),
        ),
    ]
